action.yml: slack failure

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -244,6 +244,23 @@ runs:
       with:
         github_token: ${{ inputs.github_token }}
         assignees: ${{ inputs.assignees }}
+    - if: ${{ steps.reviewdog-enabled.outputs.value && !inputs.slack_token && hashFiles('reviewdog.fail.log') }}
+      shell: bash
+      run: |
+        set +x
+        echo -e '\033[0;31mThis action encountered an error while reporting the following findings via the Github API:'
+        cat reviewdog.fail.log | sed 's/^/\x1B[0;34m/'
+        echo -e '\033[0;31mThe failure of this action should not prevent you from merging your PR. Please report this failure to the maintainers of https://github.com/brave/security-action \033[0m'
+        exit 1
+    - uses: actions-ecosystem/action-slack-notifier@v1
+      if: ${{ steps.reviewdog-enabled.outputs.value && inputs.slack_token && hashFiles('reviewdog.fail.log') }}
+      with:
+        slack_token: ${{ inputs.slack_token }}
+        message: |
+          [semgrep] @${{ github.actor }} action failed, plz take a look. /cc ${{steps.assignees.outputs.value}}
+        channel: secops-hotspots
+        color: red
+        verbose: true
     - uses: actions-ecosystem/action-slack-notifier@v1
       if: ${{ steps.reviewdog-enabled.outputs.value && inputs.slack_token && (steps.comments-before.outputs.result != steps.comments-after.outputs.result) }}
       with:
