better self-test

diff --git a/.github/workflows/semgrep-self-test.yml b/.github/workflows/semgrep-self-test.yml
--- a/.github/workflows/semgrep-self-test.yml
+++ b/.github/workflows/semgrep-self-test.yml
@@ -14,7 +14,7 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - run: |
-          python3 -m pip --disable-pip-version-check install semgrep~=1.17.0
+          python3 -m pip --disable-pip-version-check install -r requirements.txt
         shell: bash
       - run: |
           semgrep --test --disable-version-check --strict --metrics=off \
@@ -25,4 +25,16 @@ jobs:
           semgrep --test --disable-version-check --strict --metrics=off \
             --config assets/semgrep_rules/c/ \
             t3sts/semgrep_rules/
+        shell: bash
+      - run: |
+          JSON=$(semgrep \
+            --disable-version-check --strict --metrics=off --json \
+            $(find assets/semgrep_rules -name '*.yml' -or -name '*.yaml' -not -path "assets/semgrep_rules/generated/*" | sed 's/^/-c /g') \
+            t3sts/semgrep_rules/ || true)
+          ERRORS=$(echo "$JSON" | jq '.errors' || true)
+          BADERRS=$(echo "$ERRORS" | jq '.[] | select(.level == "error")' || true)
+          if [[ -n "$BADERRS" ]]; then
+            echo "Semgrep rule / version issue: $BADERRS"
+            exit 123
+          fi
         shell: bash
